# Generated by Django 6.0.3 on 2026-03-08 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_cliente_bairro_cliente_cep_cliente_cidade_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orcamento',
            name='condicoes_pagamento',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='orcamento',
            name='observacoes',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='itemorcamento',
            name='quantidade',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
        ),
        migrations.AlterField(
            model_name='itemorcamento',
            name='tipo',
            field=models.CharField(choices=[('material', 'Material'), ('mao_de_obra', 'Mão de Obra')], default='material', max_length=20),
        ),
        migrations.AlterField(
            model_name='itemorcamento',
            name='unidade',
            field=models.CharField(default='un', max_length=20),
        ),
        migrations.AlterField(
            model_name='itemorcamento',
            name='valor_unitario',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
