# Generated by Django 6.0.3 on 2026-03-09 23:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_orcamento_condicoes_pagamento_orcamento_observacoes_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(blank=True, max_length=200)),
                ('empresa', models.CharField(blank=True, max_length=200)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('telefone', models.CharField(blank=True, max_length=20)),
                ('cpf_cnpj', models.CharField(blank=True, max_length=20)),
                ('endereco', models.CharField(blank=True, max_length=300)),
                ('logo', models.TextField(blank=True)),
                ('assinatura', models.TextField(blank=True)),
                ('cor_orcamento', models.CharField(blank=True, default='azul', max_length=20)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
