# Generated by Django 6.0.3 on 2026-03-12 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_passwordresetcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='orcamento',
            name='numero',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
